### ISSUE TITLE
Ruby errors

### ISSUE THREAD

**Issue by cshiells** [marcIhm/harp_trainer#1]
Getting this when attempting to run the program. I freshly installed ruby and ran everything in the 'install' scripts.

- [ ] <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sys/proctable (LoadError)
- [ ] from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
- [ ] from ./harpwise:13:in `<main>'

**Comment by marcIhm** [comment]
Hi, thanx for reporting !
What did/do you get on:
sudo gem install sys-proctable
when executed manually ?
I am expecting some kind of error message.
However, details for errors during installation of gems are often contained in a logfile, which is named in the terminal output error message. So you may send/look-into this file too.
And, if you are on a system other than fedora, ubuntu, wsl, this would be interesting too.

**Comment by cshiells** [comment]
I'm running an arch linux derivative.  I eventually got 'sudo gem install sys-proctable' to run without obvious error, but still got the same error running harpwise, so apparently not. I may revisit it later.

**Comment by marcIhm** [comment]
This constellation could only happen if you (ordinary user) and root use different ruby installations (which perfectly okay by itself, but not expected by my installation procedure);
such a difference would show up when executing these two lines:
```
/usr/bin/env ruby -r sys-proctable -e ''  ## will probably fail for you, in the same way as harpwise does
sudo ruby -r sys-proctable -e ''  ## will work okay (no error message), because the gem has been installed fine before
```
in that case:

`/usr/bin/env gem install sys-proctable`

should fix the issue ...

**Comment by marcIhm** [comment]
harpwise no longer depends on sys/proctable; issue should be gone now.
